/**
 * Fingerprint metadata without the path data. Components draw the real isotype with
 * <use href="/brand/fingerprint.svg#rN"> so the 60 kB of traced geometry is downloaded once,
 * cached, and never inlined in HTML, RSC payloads or client bundles.
 * The sprite is generated by scripts/prepare-assets.mjs from src/data/fingerprint.ts.
 */
export const FINGERPRINT_VIEWBOX = "253 16 1480 1969";
export const RIDGE_COUNT = 11;
export const FP_SPRITE = "/brand/fingerprint.svg";
export const RIDGES: number[] = Array.from({ length: RIDGE_COUNT }, (_, i) => i);
export const ridgeHref = (i: number) => `${FP_SPRITE}#r${i}`;
